[package]
name = "swappy"
version = "0.0.1"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = ">=2.2.0"

[[target.starknet-contract]]

[scripts]
test = "scarb fmt && scarb cairo-test"
katana = "katana"
katana-fork = "/bin/bash scripts/katana_fork.sh"