mod RouterError {
    const ALREADY_INITIALIZED: felt252 = 'ALREADY_INITIALIZED';
    const ONLY_OWNER: felt252 = 'ONLY_OWNER';
    const ROUTER_ADDRESS_UNDEFINED: felt252 = 'ROUTER_ADDRESS_UNDEFINED';
}
