name: CI

on: [pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "2.4.1"
      - run: scarb fmt --check
      - run: scarb build
      - run: scarb test